"""Phase 16.3 — In-house Jersey OCR model.

Small CNN that reads jersey numbers (1–99) from player-crop patches extracted by
the CV worker (16.7). Trained on synthetic data generated by
``scripts/generate_jersey_data.py``.

Architecture::

    Conv(3→32, 3×3) → BN → ReLU → MaxPool(2×2)
    Conv(32→64, 3×3) → BN → ReLU → MaxPool(2×2)
    Conv(64→128, 3×3) → BN → ReLU → MaxPool(2×2)
    Flatten → FC(512) → Dropout(0.4) → FC(100)
    Input: 48×48 RGB float tensor
    Output: 100-class logits (index 0 = "unknown/no-read", 1–99 = jersey number)

Quality gate: top-1 accuracy ≥ 85% on held-out synthetic crops.

Identity locking — once a track_id has produced the same reading 3 times in a row
the identity is locked; subsequent crops skip inference and return the cached number
until ``reset(track_id)`` is called (e.g., when the track is lost).

Usage::

    from models.cv.jersey_ocr import JerseyOCR

    ocr = JerseyOCR()                           # loads from default path
    number, conf, locked = ocr.update(42, crop) # crop: BGR np.ndarray (H, W, 3)
    # Once locked, returns (number, conf, True) without re-inference.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO       = Path(__file__).parents[2]
DEFAULT_PT  = _REPO / "models" / "cv" / "jersey_ocr.pt"
METRICS_JSON = _REPO / "models" / "cv" / "jersey_ocr_metrics.json"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

NUM_CLASSES   = 100   # 0=unknown, 1–99=jersey number
INPUT_SIZE    = 48    # pixels (square)
TOP1_GATE     = 0.85  # quality gate — top-1 accuracy
LOCK_READS    = 3     # consistent reads needed to lock identity
CONF_UNKNOWN  = 0.0   # confidence returned for class-0 ("unknown")
UNKNOWN_NUM   = 0     # class index and returned number for no-read


# ---------------------------------------------------------------------------
# Model definition
# ---------------------------------------------------------------------------

class JerseyOCRNet(nn.Module):
    """3-conv-block CNN → 100-class head for jersey number recognition."""

    def __init__(self) -> None:
        super().__init__()
        self.features = nn.Sequential(
            # Block 1 — 48×48 → 24×24
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Block 2 — 24×24 → 12×12
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Block 3 — 12×12 → 6×6
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
        )
        # 128 * 6 * 6 = 4608
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 6 * 6, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(512, NUM_CLASSES),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.classifier(self.features(x))


# ---------------------------------------------------------------------------
# Inference wrapper
# ---------------------------------------------------------------------------

class JerseyOCR:
    """Load and run the jersey OCR model with per-track identity locking.

    Args:
        model_path:  Path to the ``.pt`` file (state_dict).
                     Defaults to ``models/cv/jersey_ocr.pt``.
        device:      ``"cuda"``, ``"cpu"``, or ``None`` for auto-select.
        conf_thresh: Minimum softmax confidence to return a reading.
                     Below this threshold returns (0, conf, False).
        lock_reads:  Consecutive identical reads before locking identity.
    """

    def __init__(
        self,
        model_path: Path | str = DEFAULT_PT,
        device: str | None = None,
        conf_thresh: float = 0.50,
        lock_reads: int = LOCK_READS,
    ) -> None:
        model_path = Path(model_path)
        if not model_path.exists():
            raise FileNotFoundError(
                f"Jersey OCR model not found: {model_path}\n"
                "Run `uv run python scripts/gretzky.py train-jersey-ocr` to build it."
            )

        self._device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self._conf_thresh = conf_thresh
        self._lock_reads  = lock_reads

        # Load model
        self._net = JerseyOCRNet().to(self._device)
        state = torch.load(str(model_path), map_location=self._device, weights_only=True)
        self._net.load_state_dict(state)
        self._net.eval()

        # Identity locking state
        self._history: dict[int, list[int]] = defaultdict(list)
        self._locked:  dict[int, tuple[int, float]] = {}  # track_id → (number, conf)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def read(self, crop: np.ndarray) -> tuple[int, float]:
        """Predict jersey number from a single BGR crop.

        Args:
            crop: ``np.ndarray`` shape ``(H, W, 3)`` BGR uint8.

        Returns:
            ``(number, confidence)`` where ``number`` is 0–99 and
            ``confidence`` is softmax probability.  ``number=0`` means
            no confident read.
        """
        tensor = self._preprocess(crop)
        with torch.no_grad():
            logits = self._net(tensor)
            probs  = F.softmax(logits, dim=1).squeeze(0)  # (100,)

        conf_val, cls_idx = probs.max(dim=0)
        conf = float(conf_val)
        num  = int(cls_idx)

        if num == UNKNOWN_NUM or conf < self._conf_thresh:
            return UNKNOWN_NUM, conf
        return num, conf

    def update(
        self,
        track_id: int,
        crop: np.ndarray,
    ) -> tuple[int, float, bool]:
        """Read jersey number for a tracked player; apply identity locking.

        Returns:
            ``(number, confidence, locked)`` where ``locked=True`` once
            ``lock_reads`` identical readings have accumulated.  After
            locking, subsequent calls skip inference.
        """
        if track_id in self._locked:
            num, conf = self._locked[track_id]
            return num, conf, True

        num, conf = self.read(crop)
        if num != UNKNOWN_NUM:
            history = self._history[track_id]
            history.append(num)
            if len(history) > self._lock_reads:
                history.pop(0)
            if len(history) == self._lock_reads and len(set(history)) == 1:
                self._locked[track_id] = (num, conf)
                return num, conf, True

        return num, conf, False

    def reset(self, track_id: int) -> None:
        """Clear history and lock state for a track (call when track lost)."""
        self._history.pop(track_id, None)
        self._locked.pop(track_id, None)

    def reset_all(self) -> None:
        """Clear all track state."""
        self._history.clear()
        self._locked.clear()

    def is_locked(self, track_id: int) -> bool:
        return track_id in self._locked

    @property
    def device(self) -> str:
        return self._device

    def __repr__(self) -> str:
        return (
            f"JerseyOCR(device={self._device!r}, "
            f"conf_thresh={self._conf_thresh}, lock_reads={self._lock_reads})"
        )

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _preprocess(self, crop: np.ndarray) -> torch.Tensor:
        """Resize crop to INPUT_SIZE, convert BGR→RGB, normalize → tensor."""
        import cv2
        img = cv2.resize(crop, (INPUT_SIZE, INPUT_SIZE), interpolation=cv2.INTER_LINEAR)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
        # Normalize with ImageNet mean/std (synthetic data trained with same normalization)
        mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
        std  = np.array([0.229, 0.224, 0.225], dtype=np.float32)
        img  = (img - mean) / std
        tensor = torch.from_numpy(img).permute(2, 0, 1).unsqueeze(0).to(self._device)
        return tensor


# ---------------------------------------------------------------------------
# Quality gate
# ---------------------------------------------------------------------------

def check_quality_gate(metrics: dict | None = None) -> tuple[bool, float]:
    """Return (passed, top1_acc) checking the ≥ 85% top-1 accuracy gate.

    If no metrics file exists, returns (False, 0.0).
    """
    import json
    if metrics is None:
        if not METRICS_JSON.exists():
            return False, 0.0
        with open(METRICS_JSON) as fh:
            metrics = json.load(fh)
    if not metrics:
        return False, 0.0
    top1 = float(metrics.get("top1_acc", 0.0))
    return top1 >= TOP1_GATE, top1
