"""Weekly warm-start retrain of the YOLO player+puck detector.

Merges the HockeyAI base dataset with the cached puck pseudo-labels written
at runtime by ``PuckPseudoCache`` and warm-starts training from the current
``models/cv/player_detector.pt``.

The new weights are only promoted if the held-out HockeyAI validation
mAP@0.5 does not regress below ``(current - tolerance)`` — so a bad batch
of pseudo-labels cannot quietly degrade the live detector.

Usage
-----
    uv run python scripts/gretzky.py retrain-cv
    uv run python scripts/gretzky.py retrain-cv -- --epochs 30 --dry-run
    uv run python scripts/gretzky.py retrain-cv -- --tolerance 0.0   # strict: no regression at all
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from models.cv.player_detector import DEFAULT_PT, METRICS_JSON, MAP50_GATE

CV_ROOT     = _REPO / "data" / "cv_training"
BASE_YAML   = CV_ROOT / "dataset.yaml"
PSEUDO_ROOT = CV_ROOT / "pseudo_labels"
MERGED_YAML = CV_ROOT / "dataset.retrain.yaml"
RUNS_DIR    = _REPO / "runs" / "cv_detector"

REGRESSION_TOLERANCE = 0.005    # default: allow ≤ 0.5 pt mAP@0.5 dip


# ---------------------------------------------------------------------------
# Dataset discovery + merged YAML
# ---------------------------------------------------------------------------

def _discover_weeks() -> list[Path]:
    if not PSEUDO_ROOT.is_dir():
        return []
    return sorted(
        wk for wk in PSEUDO_ROOT.iterdir()
        if wk.is_dir()
        and (wk / "images").is_dir()
        and any((wk / "images").glob("*.jpg"))
    )


def _write_merged_yaml(weeks: list[Path]) -> Path:
    train_paths = ["images/train"]
    for wk in weeks:
        rel = wk.relative_to(CV_ROOT) / "images"
        train_paths.append(rel.as_posix())

    lines = [
        "# GRTZKY retrain-cv merged dataset (HockeyAI + pseudo-labels)",
        "# Auto-generated by scripts/retrain_cv_detector.py",
        "",
        f"path: {CV_ROOT.resolve()}",
        "train:",
    ]
    lines += [f"  - {p}" for p in train_paths]
    lines += [
        "val: images/val",
        "",
        "nc: 6",
        "names:",
        "  0: player_home",
        "  1: player_away",
        "  2: goalie_home",
        "  3: goalie_away",
        "  4: referee",
        "  5: puck",
    ]
    MERGED_YAML.write_text("\n".join(lines) + "\n")
    return MERGED_YAML


# ---------------------------------------------------------------------------
# Metrics helpers
# ---------------------------------------------------------------------------

def _prev_map50() -> float:
    if not METRICS_JSON.exists():
        return 0.0
    try:
        return float(json.loads(METRICS_JSON.read_text()).get("map50", 0.0))
    except Exception:
        return 0.0


def _extract_metrics(results) -> dict:
    rd = getattr(results, "results_dict", {}) or {}
    def _g(k: str, alt: str = "") -> float:
        return float(rd.get(k, rd.get(alt, 0.0)))
    return {
        "map50":     _g("metrics/mAP50(B)",     "mAP50"),
        "map50_95":  _g("metrics/mAP50-95(B)",  "mAP50-95"),
        "precision": _g("metrics/precision(B)", "precision"),
        "recall":    _g("metrics/recall(B)",    "recall"),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--epochs",    type=int,   default=20)
    ap.add_argument("--batch",     type=int,   default=16)
    ap.add_argument("--imgsz",     type=int,   default=640)
    ap.add_argument("--lr",        type=float, default=0.001,
                    help="warm-start LR (default 0.001, 10× lower than fresh train)")
    ap.add_argument("--patience",  type=int,   default=10)
    ap.add_argument("--device",    default=None)
    ap.add_argument("--tolerance", type=float, default=REGRESSION_TOLERANCE,
                    help="max allowed regression in mAP@0.5 before rejecting new weights")
    ap.add_argument("--dry-run",   action="store_true",
                    help="report what would run; do not train")
    args = ap.parse_args(argv)

    # ── Pre-flight ────────────────────────────────────────────────────────────
    if not DEFAULT_PT.exists():
        print(f"[retrain-cv] No existing detector at {DEFAULT_PT}.")
        print("[retrain-cv] Run `gretzky.py train-cv-detector` first.")
        sys.exit(1)

    if not BASE_YAML.exists():
        print(f"[retrain-cv] Base dataset.yaml missing at {BASE_YAML}.")
        print("[retrain-cv] Run `python scripts/fetch_hockey_ai.py` first.")
        sys.exit(1)

    weeks = _discover_weeks()
    if not weeks:
        print("[retrain-cv] No pseudo-labels cached yet — nothing to train on.")
        return

    total_pseudo = sum(len(list((wk / "images").glob("*.jpg"))) for wk in weeks)
    prev = _prev_map50()

    print(f"[retrain-cv] Pseudo-label weeks : {len(weeks)} ({', '.join(wk.name for wk in weeks)})")
    print(f"[retrain-cv] Pseudo-label frames: {total_pseudo:,}")
    print(f"[retrain-cv] Current mAP@0.5   : {prev:.4f}")
    print(f"[retrain-cv] Regression floor  : {max(0.0, prev - args.tolerance):.4f} (tol={args.tolerance})")

    merged = _write_merged_yaml(weeks)
    print(f"[retrain-cv] Merged yaml → {merged}")

    if args.dry_run:
        print("[retrain-cv] --dry-run: stopping before training.")
        return

    # ── Backup current weights ────────────────────────────────────────────────
    backup = DEFAULT_PT.with_suffix(".prev.pt")
    shutil.copy2(DEFAULT_PT, backup)
    print(f"[retrain-cv] Backed up current weights → {backup}")

    # ── Warm-start training ───────────────────────────────────────────────────
    from ultralytics import YOLO
    import torch

    device = args.device or ("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[retrain-cv] Device: {device}")
    print(f"[retrain-cv] Warm-starting from {DEFAULT_PT.name}")

    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    model = YOLO(str(DEFAULT_PT))

    results = model.train(
        data=str(merged),
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=device,
        project=str(RUNS_DIR),
        name="retrain",
        exist_ok=True,
        freeze=0,               # unfreeze everything — warm-start fine-tune
        lr0=args.lr,
        lrf=0.01,
        patience=args.patience,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        fliplr=0.5,
        val=True,
        plots=True,
        save=True,
        verbose=True,
    )

    new_metrics = _extract_metrics(results)
    new_map50   = new_metrics["map50"]
    delta       = new_map50 - prev
    floor       = prev - args.tolerance

    print()
    print(f"[retrain-cv] New mAP@0.5 : {new_map50:.4f}  (Δ {delta:+.4f})")

    # ── Promotion gate ────────────────────────────────────────────────────────
    if new_map50 < floor:
        candidate = Path(results.save_dir) / "weights" / "best.pt"
        print(f"[retrain-cv] ✗ Regression — keeping previous weights.")
        print(f"[retrain-cv]   Candidate lives at {candidate}")
        sys.exit(1)

    best = Path(results.save_dir) / "weights" / "best.pt"
    shutil.copy2(best, DEFAULT_PT)

    out_metrics = {
        **new_metrics,
        "model_path":           str(DEFAULT_PT),
        "backbone":             "player_detector.pt (warm-start)",
        "epochs":               args.epochs,
        "pseudo_label_weeks":   [wk.name for wk in weeks],
        "pseudo_label_frames":  total_pseudo,
        "previous_map50":       prev,
        "delta_map50":          delta,
        "quality_gate": {
            "threshold": MAP50_GATE,
            "passed":    new_map50 >= MAP50_GATE,
            "map50":     new_map50,
        },
    }
    METRICS_JSON.write_text(json.dumps(out_metrics, indent=2))

    gate_sym = "✓" if new_map50 >= MAP50_GATE else "·"
    gate_msg = "PASS" if new_map50 >= MAP50_GATE else f"below {MAP50_GATE} gate"
    print(f"[retrain-cv] ✓ Promoted {best.name} → {DEFAULT_PT}")
    print(f"[retrain-cv]   Gate {gate_sym} {gate_msg}")


if __name__ == "__main__":
    main()
